In [2]:
import pandas as pd
arquivo = pd.read_csv('C:/Users/ferag/Downloads/MachineLearning/wine_dataset.csv')

In [5]:
arquivo.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality style  
0      9.4        5   red  
1      9.8        5   red  
2      9.8        5   red  
3      9.8        6   red  
4      9.4        5   red

In [6]:
arquivo ['style'] = arquivo['style'].replace('red', 0)

In [8]:
arquivo['style'] = arquivo['style'].replace('white', 1).infer_objects()


In [9]:
arquivo

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  style  
0         9.4        5      0  
1         9.8        5      0  
2         9.8        5      0  
3         9.8        6      0  
4         9.4        5      0  
...       ...      ...    ...  
6492     11.2        6      1  
6493      9.6        5      1  
6494      9.4        6      1  
6495     12.8        7      1  
6496     11.8        6      1  

[6497 rows x 13 columns]

In [10]:
y = arquivo['style']
x = arquivo.drop('style', axis = 1)

In [12]:
x

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
6492     11.2        6  
6493      9.6        5  
6494      9.4        6  
6495     12.8        7  
6496     11.8        6  

[6497 rows x 12 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [14]:
x_treino.shape

(4547, 12)

In [19]:
from sklearn.ensemble import ExtraTreesClassifier

modelo = ExtraTreesClassifier(n_estimators=100)
modelo.fit(x_treino, y_treino)

resultado = modelo.score(x_teste, y_teste)
print("Acuracia: ", resultado)

Acuracia:  0.997948717948718


In [20]:
x_teste[400:403]

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
2797            7.1             0.260         0.32           14.45      0.074   
729             6.4             0.865         0.03            3.20      0.071   
1470           10.0             0.690         0.11            1.40      0.084   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
2797                 29.0                 107.0  0.99800  2.96       0.42   
729                  27.0                  58.0  0.99500  3.61       0.49   
1470                  8.0                  24.0  0.99578  2.88       0.47   

      alcohol  quality  
2797      9.2        6  
729      12.7        6  
1470      9.7        5

In [21]:
previsoes = modelo.predict(x_teste[400:403])

In [22]:
previsoes

array([1, 0, 0], dtype=int64)

In [23]:
y_teste[400:403]

2797    1
729     0
1470    0
Name: style, dtype: int64

In [24]:
previsoes2 = modelo.predict(x_teste[400:420])

In [25]:
x_teste[400:420]

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
2797            7.1             0.260         0.32           14.45      0.074   
729             6.4             0.865         0.03            3.20      0.071   
1470           10.0             0.690         0.11            1.40      0.084   
2330            6.2             0.250         0.48           10.00      0.044   
3097            7.7             0.270         0.49            1.80      0.041   
3285            7.4             0.260         0.37            9.40      0.047   
166             6.8             0.640         0.10            2.10      0.085   
3932            6.8             0.370         0.28            1.90      0.024   
620             8.3             0.540         0.24            3.40      0.076   
1376            8.2             0.885         0.20            1.40      0.086   
6476            5.9             0.540         0.00            0.80      0.032   
3561            8.2             0.210         0.48            1.40      0.041   
3579            7.6             0.200         0.30           14.20      0.056   
3260            6.7             0.260         0.49            8.30      0.047   
5801            6.7             0.240         0.31            2.30      0.044   
4408            5.8             0.320         0.31            2.70      0.049   
2727            5.7             0.100         0.27            1.30      0.047   
2041            6.0             0.250         0.28            2.20      0.026   
4205            7.2             0.200         0.36            2.50      0.028   
3824            7.6             0.230         0.26           15.30      0.067   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
2797                 29.0                 107.0  0.99800  2.96       0.42   
729                  27.0                  58.0  0.99500  3.61       0.49   
1470                  8.0                  24.0  0.99578  2.88       0.47   
2330                 78.0                 240.0  0.99655  3.25       0.47   
3097                 23.0                  86.0  0.99140  3.16       0.42   
3285                 42.0                 147.0  0.99820  3.46       0.72   
166                  18.0                 101.0  0.99560  3.34       0.52   
3932                 64.0                 106.0  0.98993  3.45       0.60   
620                  16.0                 112.0  0.99760  3.27       0.61   
1376                  7.0                  31.0  0.99460  3.11       0.46   
6476                 12.0                  82.0  0.99286  3.25       0.36   
3561                 11.0                  99.0  0.99580  3.17       0.57   
3579                 53.0                 212.5  0.99900  3.14       0.46   
3260                 54.0                 191.0  0.99540  3.23       0.40   
5801                 37.0                 113.0  0.99013  3.29       0.46   
4408                 25.0                 153.0  0.99067  3.44       0.73   
2727                 21.0                 100.0  0.99280  3.27       0.46   
2041                 54.0                 126.0  0.98980  3.43       0.65   
4205                 22.0                 157.0  0.99380  3.48       0.49   
3824                 32.0                 166.0  0.99860  3.03       0.44   

      alcohol  quality  
2797      9.2        6  
729      12.7        6  
1470      9.7        5  
2330      9.5        6  
3097     12.5        6  
3285     10.0        5  
166      10.2        5  
3932     12.6        8  
620       9.4        5  
1376     10.0        5  
6476      8.8        5  
3561      9.9        5  
3579      8.9        8  
3260     10.3        6  
5801     12.9        6  
4408     12.2        7  
2727      9.5        5  
2041     12.9        8  
4205     10.6        6  
3824      9.2        4

In [26]:
y_teste[400:420]

2797    1
729     0
1470    0
2330    1
3097    1
3285    1
166     0
3932    1
620     0
1376    0
6476    1
3561    1
3579    1
3260    1
5801    1
4408    1
2727    1
2041    1
4205    1
3824    1
Name: style, dtype: int64

In [27]:
previsoes2

array([1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [28]:
resultado

0.997948717948718

In [29]:
print("hello world")

hello world


In [30]:
nova_linha = {
    'fixed_acidity': 7.0,
    'volatile_acidity': 0.4,
    'citric_acid': 0.3,
    'residual_sugar': 2.0,
    'chlorides': 0.08,
    'free_sulfur_dioxide': 15,
    'total_sulfur_dioxide': 40,
    'density': 0.995,
    'pH': 3.3,
    'sulphates': 0.6,
    'alcohol': 11.0,
    'quality': 6,
    'style': 0 }

In [36]:
arquivo.loc[len(arquivo)] = nova_linha

In [41]:
nova_linha_features = arquivo.iloc[-1, :-1].values.reshape(1, -1)

In [43]:
temp_df = pd.DataFrame(nova_linha_features, columns=x.columns)

In [44]:
previsao_nova_linha = modelo.predict(temp_df)

In [45]:
previsao_nova_linha

array([0], dtype=int64)

In [46]:
arquivo

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   
6497            7.0              0.40         0.30             2.0      0.080   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   
6497                 15.0                  40.0  0.99500  3.30       0.60   

      alcohol  quality  style  
0         9.4        5      0  
1         9.8        5      0  
2         9.8        5      0  
3         9.8        6      0  
4         9.4        5      0  
...       ...      ...    ...  
6493      9.6        5      1  
6494      9.4        6      1  
6495     12.8        7      1  
6496     11.8        6      1  
6497     11.0        6      0  

[6498 rows x 13 columns]

In [47]:
print("Nova linha adicionada e testada!")

Nova linha adicionada e testada!
